default_install_hook_types:
  - commit-msg
  - pre-commit
  - pre-push
repos:
# Make sure linting and formatting is done before commit.
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.8
  hooks:
    # Run the linter.
    - id: ruff
      args: ['--fix']
      stages: [pre-commit]
    # Run the formatter.
    - id: ruff-format
      stages: [pre-commit]
# Make sure requirements.txt is up to date.
- repo: https://github.com/pdm-project/pdm
  rev: 2.15.1
  hooks:
    - id: pdm-lock-check
      stages: [pre-commit]
    - id: pdm-export
      args: ['-o', 'requirements.txt', '--without-hashes']
      files: ^pdm.lock$
      stages: [pre-commit]
# Make sure
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.16.0
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-conventional']
